{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "SqlServer localhost Bank",
        "connectionString": "Provider=SQLOLEDB;Data Source=DESKTOP-LD1MQL2;Initial Catalog=Bank;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "DimCards",
        "columns": [
          {
            "name": "CardKey",
            "dataType": "int64",
            "sourceColumn": "CardKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CardID",
            "dataType": "int64",
            "sourceColumn": "CardID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "UserKey",
            "dataType": "int64",
            "sourceColumn": "UserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CardBrand",
            "dataType": "string",
            "sourceColumn": "CardBrand",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CardType",
            "dataType": "string",
            "sourceColumn": "CardType",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ExpireDateKey",
            "dataType": "int64",
            "sourceColumn": "ExpireDateKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "HasChip",
            "dataType": "string",
            "sourceColumn": "HasChip",
            "sourceProviderType": "WChar"
          },
          {
            "name": "NumOfCards",
            "dataType": "int64",
            "sourceColumn": "NumOfCards",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CreditLimit",
            "dataType": "int64",
            "sourceColumn": "CreditLimit",
            "sourceProviderType": "Integer"
          },
          {
            "name": "AccountOpenDateKey",
            "dataType": "int64",
            "sourceColumn": "AccountOpenDateKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "LastPinChangeYear",
            "dataType": "int64",
            "sourceColumn": "LastPinChangeYear",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "DimCards",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimCards].*   FROM [DWH].[DimCards] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimCards].*   FROM [DWH].[DimCards] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimCards"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimChip",
        "columns": [
          {
            "name": "ChipKey",
            "dataType": "int64",
            "sourceColumn": "ChipKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Chip",
            "dataType": "string",
            "sourceColumn": "Chip",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimChip",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimChip].*   FROM [DWH].[DimChip] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimChip].*   FROM [DWH].[DimChip] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimChip"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimCity",
        "columns": [
          {
            "name": "CityKey",
            "dataType": "int64",
            "sourceColumn": "CityKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimCity",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimCity].*   FROM [DWH].[DimCity] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimCity].*   FROM [DWH].[DimCity] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimCity"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimErrors",
        "columns": [
          {
            "name": "ErrorsKey",
            "dataType": "int64",
            "sourceColumn": "ErrorsKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Error",
            "dataType": "string",
            "sourceColumn": "Error",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimErrors",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimErrors].*   FROM [DWH].[DimErrors] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimErrors].*   FROM [DWH].[DimErrors] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimErrors"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimMCC",
        "columns": [
          {
            "name": "MCCKey",
            "dataType": "int64",
            "sourceColumn": "MCCKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MCC_Code",
            "dataType": "int64",
            "sourceColumn": "MCC_Code",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MCC",
            "dataType": "string",
            "sourceColumn": "MCC",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimMCC",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimMCC].*   FROM [DWH].[DimMCC] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimMCC].*   FROM [DWH].[DimMCC] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimMCC"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimState",
        "columns": [
          {
            "name": "StateKey",
            "dataType": "int64",
            "sourceColumn": "StateKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StateCode",
            "dataType": "string",
            "sourceColumn": "StateCode",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimState",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimState].*   FROM [DWH].[DimState] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimState].*   FROM [DWH].[DimState] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimState"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimStreet",
        "columns": [
          {
            "name": "StreetKey",
            "dataType": "int64",
            "sourceColumn": "StreetKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StreetName",
            "dataType": "string",
            "sourceColumn": "StreetName",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimStreet",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimStreet].*   FROM [DWH].[DimStreet] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimStreet].*   FROM [DWH].[DimStreet] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimStreet"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimUsers",
        "columns": [
          {
            "name": "UserKey",
            "dataType": "int64",
            "sourceColumn": "UserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age",
            "sourceProviderType": "Integer"
          },
          {
            "name": "RetirementAge",
            "dataType": "int64",
            "sourceColumn": "RetirementAge",
            "sourceProviderType": "Integer"
          },
          {
            "name": "YearOfBirth",
            "dataType": "int64",
            "sourceColumn": "YearOfBirth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MonthOfBirth",
            "dataType": "int64",
            "sourceColumn": "MonthOfBirth",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "sourceProviderType": "WChar"
          },
          {
            "name": "StreetNum",
            "dataType": "int64",
            "sourceColumn": "StreetNum",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StreetKey",
            "dataType": "int64",
            "sourceColumn": "StreetKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "sourceProviderType": "Double"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "sourceProviderType": "Double"
          },
          {
            "name": "PerCapitaIncome",
            "dataType": "int64",
            "sourceColumn": "PerCapitaIncome",
            "sourceProviderType": "Integer"
          },
          {
            "name": "YearlyIncome",
            "dataType": "int64",
            "sourceColumn": "YearlyIncome",
            "sourceProviderType": "Integer"
          },
          {
            "name": "TotalDebt",
            "dataType": "int64",
            "sourceColumn": "TotalDebt",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CreditScore",
            "dataType": "int64",
            "sourceColumn": "CreditScore",
            "sourceProviderType": "Integer"
          },
          {
            "name": "NumOfCreditCards",
            "dataType": "int64",
            "sourceColumn": "NumOfCreditCards",
            "sourceProviderType": "Integer"
          },
          {
            "type": "calculated",
            "name": "AgeGroup",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              " ",
              "SWITCH(",
              "    TRUE(),",
              "    DimUsers[Age] < 20, \"<20\",",
              "    DimUsers[Age] >= 20 && DimUsers[Age] < 30, \"20-29\",",
              "    DimUsers[Age] >= 30 && DimUsers[Age] < 40, \"30-39\",",
              "    DimUsers[Age] >= 40 && DimUsers[Age] < 50, \"40-49\",",
              "    DimUsers[Age] >= 50 && DimUsers[Age] < 60, \"50-59\",",
              "    DimUsers[Age] >= 60, \"60+\",",
              "    \"Unknown\"",
              ")"
            ]
          },
          {
            "type": "calculated",
            "name": "Risk",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    DimUsers[CreditScore] >= 750, \"Low Risk\",",
              "    DimUsers[CreditScore] >= 650 && DimUsers[CreditScore] < 750, \"Medium Risk\",",
              "    DimUsers[CreditScore] < 650, \"High Risk\",",
              "    \"Unknown\"",
              ")"
            ]
          },
          {
            "type": "calculated",
            "name": "YearlyIncomeGroups",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    DimUsers[YearlyIncome] < 20000, \"<20K\",",
              "    DimUsers[YearlyIncome] >= 20000 && DimUsers[YearlyIncome] < 50000, \"20K-49K\",",
              "    DimUsers[YearlyIncome] >= 50000 && DimUsers[YearlyIncome] < 100000, \"50K-99K\",",
              "    DimUsers[YearlyIncome] >= 100000 && DimUsers[YearlyIncome] < 200000, \"100K-199K\",",
              "    DimUsers[YearlyIncome] >= 200000, \"200K+\",",
              "    \"Unknown\"",
              ")"
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimUsers",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimUsers].*   FROM [DWH].[DimUsers] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "measures": [
          {
            "name": "Females",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(DimUsers),DimUsers[Gender] = \"Female\"",
              ")"
            ]
          },
          {
            "name": "AVG Age Male",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(DimUsers[Age]),DimUsers[Gender] = \"Male\"",
              ")"
            ]
          },
          {
            "name": "AVG Age Female",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE(DimUsers[Age]),DimUsers[Gender] = \"Female\"",
              ")"
            ]
          },
          {
            "name": "Males",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(DimUsers),DimUsers[Gender] = \"Male\"",
              ")"
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimUsers].*   FROM [DWH].[DimUsers] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimUsers"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "FactTransactions",
        "columns": [
          {
            "name": "TransactionKey",
            "dataType": "int64",
            "sourceColumn": "TransactionKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "UserKey",
            "dataType": "int64",
            "sourceColumn": "UserKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CardKey",
            "dataType": "int64",
            "sourceColumn": "CardKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "Amount",
            "sourceProviderType": "Double"
          },
          {
            "name": "UseChipKey",
            "dataType": "int64",
            "sourceColumn": "UseChipKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MerchantID",
            "dataType": "int64",
            "sourceColumn": "MerchantID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "CityKey",
            "dataType": "int64",
            "sourceColumn": "CityKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "StateKey",
            "dataType": "int64",
            "sourceColumn": "StateKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ZIP",
            "dataType": "int64",
            "sourceColumn": "ZIP",
            "sourceProviderType": "Integer"
          },
          {
            "name": "MCCKey",
            "dataType": "int64",
            "sourceColumn": "MCCKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "ErrorsKey",
            "dataType": "int64",
            "sourceColumn": "ErrorsKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Target",
            "dataType": "int64",
            "sourceColumn": "Target",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "FactTransactions",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[FactTransactions].*   FROM [DWH].[FactTransactions] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "measures": [
          {
            "name": "Transactions Count",
            "expression": [
              "",
              "COUNTROWS(FactTransactions)"
            ]
          },
          {
            "name": "Total Amount",
            "expression": [
              "",
              "SUM(FactTransactions[Amount])"
            ]
          },
          {
            "name": "Average Transaction Amount",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Amount],",
              "    [Transactions Count]",
              ")"
            ]
          },
          {
            "name": "Failed Transactions",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(FactTransactions),",
              "   FactTransactions[ErrorsKey] <>10",
              ")"
            ]
          },
          {
            "name": "Successful Transactions",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(FactTransactions),",
              "   FactTransactions[ErrorsKey] =10",
              ")"
            ]
          },
          {
            "name": "Success Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    [Successful Transactions],",
              "    [Transactions Count]",
              ")"
            ]
          },
          {
            "name": "Failure Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    [Failed Transactions],",
              "    [Transactions Count]",
              ")"
            ]
          },
          {
            "name": "Active Users",
            "expression": [
              "",
              "DISTINCTCOUNT(FactTransactions[UserKey])"
            ]
          },
          {
            "name": "Active Cards",
            "expression": [
              "",
              "DISTINCTCOUNT(FactTransactions[CardKey])"
            ]
          },
          {
            "name": "Transactions per User",
            "expression": [
              "",
              "DIVIDE(",
              "    [Transactions Count],",
              "    [Active Users]",
              ")"
            ]
          },
          {
            "name": "Spend per User",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Amount],",
              "    [Active Users]",
              ")"
            ]
          },
          {
            "name": "Targeted Transactions",
            "expression": [
              "",
              "CALCULATE(",
              "    [Transactions Count],",
              "    FactTransactions[Target] = 1",
              ")"
            ]
          },
          {
            "name": "Target Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    [Targeted Transactions],",
              "    [Transactions Count]",
              ")"
            ]
          },
          {
            "name": "Total Amount LY",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Amount],",
              "    SAMEPERIODLASTYEAR(DimDate[Date])",
              ")"
            ]
          },
          {
            "name": "YoY Growth %",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Amount] - [Total Amount LY],",
              "    [Total Amount LY]",
              ")"
            ]
          },
          {
            "name": "Amount Contribution %",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Amount],",
              "    CALCULATE(",
              "        [Total Amount],",
              "        ALLSELECTED(DimMCC)",
              "    )",
              ")"
            ]
          },
          {
            "name": "Target Amount",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Amount],",
              "    FactTransactions[Target] = 1",
              ")"
            ]
          },
          {
            "name": "Target Failure Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        [Failed Transactions],",
              "        FactTransactions[Target] = 1",
              "    ),",
              "    [Targeted Transactions]",
              ")"
            ]
          },
          {
            "name": "Frauds",
            "expression": " SUM(FactTransactions[Target])"
          },
          {
            "name": "Natural",
            "expression": " COUNTROWS(FactTransactions) - [Frauds]"
          },
          {
            "name": "Pass Amount",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(FactTransactions[Amount]),FactTransactions[ErrorsKey]=10",
              ")"
            ]
          },
          {
            "name": "Failed Amount",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(FactTransactions[Amount]),FactTransactions[ErrorsKey]<>10",
              ")"
            ]
          },
          {
            "name": "Visa",
            "expression": " CALCULATE(sum(FactTransactions[Amount]), DimCards[CardBrand] = \"Visa\")"
          },
          {
            "name": "MasterCard",
            "expression": " CALCULATE(sum(FactTransactions[Amount]), DimCards[CardBrand] = \"MasterCard\")"
          },
          {
            "name": "Amex",
            "expression": " CALCULATE(sum(FactTransactions[Amount]), DimCards[CardBrand] = \"Amex\")"
          },
          {
            "name": "Discover",
            "expression": " CALCULATE(sum(FactTransactions[Amount]), DimCards[CardBrand] = \"Discover\")"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[FactTransactions].*   FROM [DWH].[FactTransactions] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "FactTransactions"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DateTime",
            "dataType": "string",
            "sourceColumn": "Date",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Hour",
            "dataType": "int64",
            "sourceColumn": "Hour",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "date_",
            "formatString": "General Date",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "DimDate1",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " \t\t\t\tSELECT [DWH].[DimDate].*   FROM [DWH].[DimDate] ",
              "dataSource": "SqlServer localhost Bank"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month"
              },
              {
                "name": "Day",
                "ordinal": 2,
                "column": "Day"
              },
              {
                "name": "Hour",
                "ordinal": 3,
                "column": "Hour"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " \t\t\t\tSELECT [DWH].[DimDate].*   FROM [DWH].[DimDate] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "DimDate"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "DWH"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e6349f02-4640-493f-a129-c34f16855eef",
        "fromTable": "DimUsers",
        "fromColumn": "StreetKey",
        "toTable": "DimStreet",
        "toColumn": "StreetKey"
      },
      {
        "name": "39e63bd0-8c2d-40bb-ba1f-289327e9f012",
        "fromTable": "DimCards",
        "fromColumn": "AccountOpenDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "48558102-937d-4762-8650-b7ddad733afd",
        "fromTable": "DimCards",
        "fromColumn": "ExpireDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "32930a08-f63d-400d-a518-81c4d815345d",
        "fromTable": "FactTransactions",
        "fromColumn": "MCCKey",
        "toTable": "DimMCC",
        "toColumn": "MCCKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "6f347ef8-1db9-428e-a30f-fc2bda20f864",
        "fromTable": "FactTransactions",
        "fromColumn": "CardKey",
        "toTable": "DimCards",
        "toColumn": "CardKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "6e598231-bbd8-4c5b-a9b3-0e96f2b61a06",
        "fromTable": "FactTransactions",
        "fromColumn": "UserKey",
        "toTable": "DimUsers",
        "toColumn": "UserKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2cf92e33-3c5f-4243-afaf-51bc9cdaecac",
        "fromTable": "FactTransactions",
        "fromColumn": "ErrorsKey",
        "toTable": "DimErrors",
        "toColumn": "ErrorsKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "364451ce-2148-4e60-ab3f-4803dd55e5ea",
        "fromTable": "FactTransactions",
        "fromColumn": "StateKey",
        "toTable": "DimState",
        "toColumn": "StateKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "35d57cfc-30bc-4ac0-b162-024920dd8fca",
        "fromTable": "FactTransactions",
        "fromColumn": "UseChipKey",
        "toTable": "DimChip",
        "toColumn": "ChipKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d0a5ec6e-c6af-4cf2-9bd9-4b4ee7b50933",
        "fromTable": "FactTransactions",
        "fromColumn": "DateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "0ea40e02-b85b-424b-8edf-cd101d28323e",
        "fromTable": "FactTransactions",
        "fromColumn": "CityKey",
        "toTable": "DimCity",
        "toColumn": "CityKey",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}